/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DropDown: typeof import('./components/drop-down/drop-down.vue')['default']
    IAntDesignCaretDownOutlined: typeof import('~icons/ant-design/caret-down-outlined')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectFolder: typeof import('./components/select-folder/select-folder.vue')['default']
  }
}
