import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { dir } from 'i18next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import { ThemeStoreProvider } from '@/providers/theme-store';
import { Languages } from '@/config';
import { PageProps } from '@/interfaces';
import '@/assets/styles/global.scss';
import MuiTheme from '@/config/mui-theme';

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return Languages.map((lng) => ({ lng }));
}

export default function RootLayout({
  children,
  params: { lng },
}: Readonly<
  PageProps & {
    children: React.ReactNode;
  }
>) {
  return (
    <html className={roboto.variable} lang={lng} dir={dir(lng)}>
      <body className={inter.className} suppressHydrationWarning>
        <AppRouterCacheProvider>
          <ThemeProvider theme={MuiTheme}>
            <ThemeStoreProvider>{children}</ThemeStoreProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
